[WIP] start to implement the new logic (validation, parsing and bit convers…
radicalbit/nsdb-kafka-connect pull request #8
Opened 2019-12-06 17:17 UTC by riccardo14

…ion interface) + test

2019-12-09 11:03 UTC, riccardo14 commented
In this PR a new mapping format is introduced as an alternative to kcql.  All the new props introduced are in dotted notation. New validators and data structures are implemented.

2019-12-09 11:18 UTC, maocorte commented on src/main/scala/io/radicalbit/nsdb/connector/kafka/sink/conf/NSDbConfigs.scala
> +        "Semantic Delivery",
non blocking comment: could be maybe used some constants to define the config groups

2019-12-09 11:19 UTC, maocorte approved these changes

2019-12-09 11:35 UTC, spi-x-i approved these changes

2019-12-09 11:35 UTC, spi-x-i commented on src/main/scala/io/radicalbit/nsdb/connector/kafka/sink/conf/MappingConfUtility.scala
> +    * @param configs
missing doc

2019-12-09 13:32 UTC, saveveltri commented on src/main/scala/io/radicalbit/nsdb/connector/kafka/sink/NSDbSinkWriter.scala
> +                           kcqls: Array[MappingInterface],
since we used a supertype as the array type, we should rename the parameter accordingly

2019-12-09 13:38 UTC, saveveltri commented on src/main/scala/io/radicalbit/nsdb/connector/kafka/sink/conf/DottedNotationValidator.scala
> +  private val dottedNotation = "^[a-zA-Z0-9_]*\\.[a-zA-Z0-9_]*$".r
maybe we can improve this regex in order to avoid to split the string by "," and validate the single token like we do below

2019-12-09 13:42 UTC, saveveltri commented on src/main/scala/io/radicalbit/nsdb/connector/kafka/sink/conf/NSDbConfigs.scala
> +  // inner property
we should avoid the inner word, to me at least it's misleading. I guess we can just remove the word inner and everything will be more clear. It's my opinion, others are welcome

2019-12-09 13:44 UTC, saveveltri commented on src/main/scala/io/radicalbit/nsdb/connector/kafka/sink/conf/MappingConfUtility.scala
> +  def validateAndParseMappingsConfig(configs: Map[String, ConfigValue]): (Type, Iterable[String]) = {
why the iterable if we return a list?

2019-12-09 13:45 UTC, saveveltri commented on src/main/scala/io/radicalbit/nsdb/connector/kafka/sink/conf/Constants.scala
> +  object Type {
MappingType?

2019-12-09 13:47 UTC, saveveltri requested changes
The overall structure seems good. Left some comments. Also, the readme must be enriched with the new configuration method available

2019-12-09 16:04 UTC, saveveltri commented on src/main/scala/io/radicalbit/nsdb/connector/kafka/sink/conf/DottedNotationValidator.scala
> +  private val dottedNotation = "[a-zA-Z0-9_]+\\.[a-zA-Z0-9_]+(,[a-zA-Z0-9_]+\\.[a-zA-Z0-9_]+)*".r
much better. I will open a discussion about the character allowed in topics and fields so that we can finalize this regexp accordingly

2019-12-09 16:08 UTC, saveveltri commented on src/main/scala/io/radicalbit/nsdb/connector/kafka/sink/conf/DottedNotationValidator.scala
> +  private val dottedNotation = "[a-zA-Z0-9_]+\\.[a-zA-Z0-9_]+(,[a-zA-Z0-9_]+\\.[a-zA-Z0-9_]+)*".r
dottedNotation is defined twice in two different class. Here maybe we can rename it into `dottedNotationList` or somethign similar

2019-12-09 16:09 UTC, saveveltri commented on src/main/scala/io/radicalbit/nsdb/connector/kafka/sink/conf/MappingConfUtility.scala
> +    val dottedNotation = "[a-zA-Z0-9_]+\\.[a-zA-Z0-9_]+".r
here we can rename into dottedNotationToken or similar. Up to you, but I would avoid any naming overlapping

2019-12-09 16:11 UTC, saveveltri commented on src/main/scala/io/radicalbit/nsdb/connector/kafka/sink/conf/Constants.scala
> +  object Type {
Still an open point

2019-12-09 16:12 UTC, saveveltri approved these changes

2019-12-09 16:16 UTC, saveveltri reviewed
overall LGTM. there is one open point

in the configuration `nsdb.mapping.values` currently, only letters and number are allowed

Which special characters do we want to allow in that configuration? 

`_`, `-`, something else?

Any suggestion @spi-x-i @marcotagliabue @riccardo14 ?

2019-12-10 09:22 UTC, maocorte commented
> overall LGTM. there is one open point
> 
> in the configuration `nsdb.mapping.values` currently, only letters and number are allowed
> 
> Which special characters do we want to allow in that configuration?
> 
> `_`, `-`, something else?
> 
> Any suggestion @spi-x-i @marcotagliabue @riccardo14 ?

yep, i think that dash and underscore chars should be allowed.

2019-12-10 14:51 UTC, saveveltri commented on src/main/scala/io/radicalbit/nsdb/connector/kafka/sink/conf/DottedNotationValidator.scala
> +  private val dottedNotationList = "[a-zA-Z0-9_]+\\.[a-zA-Z0-9_]+(,[a-zA-Z0-9_]+\\.[a-zA-Z0-9_]+)*".r
does this allow the `-` character?

2019-12-10 14:51 UTC, saveveltri requested changes
cound you include some special character in test configurations?

2019-12-10 15:15 UTC, riccardo14 commented
Updated the allowed char for both regex

2019-12-11 11:44 UTC, saveveltri approved these changes

2019-12-12 11:21 UTC, merged